SELECT
    ku.TABLE_NAME,
    ku.COLUMN_NAME,
    tc.CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
    ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
WHERE ku.TABLE_NAME IN (
    'TPlanPersonal',
    'TPersonal',
    'TPlanungseinheitenPersonal'
)
ORDER BY ku.TABLE_NAME, ku.ORDINAL_POSITION;
