repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: trailing-whitespace
