repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-yaml
        args: [--unsafe]
        files: mkdocs.yml
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
