name: 📚 Build & Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - "mkdocs.yml"
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build-mkdocs:
    name: 🛠️ Build & Deploy Documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: 📦 Install Dependencies
        run: |
          uv sync --frozen --extra docs

      - name: 🚀 Build & Upload Documentation to GitHub Pages
        run: |
          uv run mkdocs gh-deploy --force
