import logging
from datetime import date
from typing import Annotated, Any

from fastapi import APIRouter, Depends

from scheduling.api.dependencies import get_timeoffice_service
from scheduling.timeoffice.service import TimeOfficeService

logger = logging.getLogger(__name__)


schedule_router = APIRouter()

# Returns the schedule generated by the solver for a given month and year.


@schedule_router.get("/schedules")
async def get_schedule(
    planning_unit: int,
    from_date: date,
    timeoffice: Annotated[TimeOfficeService, Depends(get_timeoffice_service)],
) -> dict[str, list[dict[str, Any]]]:
    return {"schedules": []}
